#!/bin/sh

lookup=google.com

if [ "x$1" != "x" ]; then
  lookup=$1
fi

echo "Creating DNS request to $lookup"
port=14238
nc -u -l $port > test-data2.udp &
dig +tries=1 +time=1 @127.0.0.1 -p $port $lookup 2>/dev/null 1>/dev/null
